
@baseUrl = http://localhost:8080/api/v1
### GET ALL EXPENSES | query: int size, int page, string sort (asc,desc)

GET {{baseUrl}}/expenses?sort=name,asc


### GET EXPENSE BY ID

GET {{baseUrl}}/expenses/10s

### DELETE EXPENSE

DELETE {{baseUrl}}/expenses?id=2

### POST EXPENSE

POST {{baseUrl}}/expenses
Content-Type: application/json

{
    "name":"Onions",
    "amount":20.00,
    "category":"Vegetables",
    "description":"Vegetables",
    "date":"2021-11-20"
}

### UPDATE EXPENSE

PUT {{baseUrl}}/expenses/3
Content-Type: application/json

{
    "name":"Pet Bill",
    "amount":400.00,
    "category":"Pet",
    "description":"pet bill",
    "date":"2021-10-15"
}

### GET EXPENSE BY CATEGORY

GET {{baseUrl}}/expenses/category?category=Bills


### GET EXPENSE BY Name

GET {{baseUrl}}/expenses/name?name=Pet


### GET EXPENSE BY Date

GET {{baseUrl}}/expenses/date?startDate=2021-10-15&endDate=2021-10-19



### CREATE USER

POST {{baseUrl}}/register
Content-Type: application/json

{
    "name":"khoa1232",
    "email":"khoans1232@gmail.com",
    "password":"Kietack!597538426"
}

### READ USER BY ID

GET {{baseUrl}}/user/4
Content-Type: application/json


### UPDATE USER BY ID

PUT {{baseUrl}}/user/4
Content-Type: application/json

{
    "name":"khoa1",
    "email":"khoans11@gmail.com",
    "age":"20"
}


### DELETE USER BY ID

DELETE {{baseUrl}}/user/4
Content-Type: application/json

