
@baseUrl = http://localhost:8080/api/v1
### GET ALL EXPENSES | query: int size, int page, string sort (asc,desc)

GET {{baseUrl}}/expenses?sort=name,asc


### GET EXPENSE BY ID

GET {{baseUrl}}/expenses/10s

### DELETE EXPENSE

DELETE {{baseUrl}}/expenses?id=2

### POST EXPENSE

POST {{baseUrl}}/expenses
Content-Type: application/json

{
    "name":"Onions",
    "amount":20.00,
    "category":"Vegetables",
    "description":"Vegetables",
    "date":"2021-11-20"
}

### UPDATE EXPENSE

PUT {{baseUrl}}/expenses/3
Content-Type: application/json

{
    "name":"Pet Bill",
    "amount":400.00,
    "category":"Pet",
    "description":"pet bill",
    "date":"2021-10-15"
}

### GET EXPENSE BY CATEGORY

GET {{baseUrl}}/expenses/category?category=Bills


### GET EXPENSE BY Name

GET {{baseUrl}}/expenses/name?name=Pet


### GET EXPENSE BY Date

GET {{baseUrl}}/expenses/date?startDate=2021-10-15&endDate=2021-10-19
