@baseUrl = http://localhost:8080/api/v1
### GET

GET {{baseUrl}}/expenses

### GET

GET {{baseUrl}}/expenses/2


### GET

GET {{baseUrl}}/expense?id=5

### DELETE EXPENSE

DELETE {{baseUrl}}/expenses?id=2

### POST EXPENSE

POST {{baseUrl}}/expenses
Content-Type: application/json

{
    "name":"Water Bill",
    "amount":900.00,
    "category":"Bills",
    "description":"water bill",
    "date":"2021-11-20"
}

### UPDATE EXPENSE

PUT {{baseUrl}}/expenses/5
Content-Type: application/json

{
    "name":"Water Bill",
    "amount":400.00,
    "category":"Bills",
    "description":"water bill",
    "date":"2021-10-15"
}